# Numpy Revise
### Author: Vu Snape


In [1]:
#lib
import numpy as np

## Day 1 

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
# check number of dimension
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [3]:
b = np.array([22, 26, 28, 10, 1, 2, 3])
print("\n")
print(b[:])
print(b[:2]) # 22 26 - bỏ số address cuối đi

print(b[-3:-1]) # 3 : -1 , 2: -2, 1 : -3

print(b[1:6:2]) 



[22 26 28 10  1  2  3]
[22 26]
[1 2]
[26 10  2]


In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

#subtract 
arrSubstract = np.subtract(arr1, arr2) #minus
#product
arrProduct = np.multiply(arr1, arr2) #product

print(arrSubstract)
print(arrProduct)

[-10  -1   8  17  26  35]
[ 200  420  660  920 1200 1500]


In [9]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

#search = value equal 4
arr = np.array([1, 2, 4, 5,66, 44])
x = np.where(arr == 4)
print(x)

#find index if x mod 2 == 1 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

[0 1 2 3]
(array([2], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


## Day 2

In [11]:
a = np.dot(6,12)  
print(a)

72


In [13]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])

print(np.matmul(a, b)) #multiple of 2 matrix: 2-D

[[4 1]
 [2 2]]


In [14]:
arr1 = np.array([[1, 2], [3, 4]])
 
print(np.linalg.det(arr1))

-2.0000000000000004


In [15]:
#transpose
v1 = [1, 2, 3, 4]
v2 = [-1, 0, 1, 3]
v3 = [0, -5, 6, 8]
w = [3, -6, 17, 11]

A = np.transpose( [v1, v2, v3] ) # reverse row to column

In [16]:
print(A)

[[ 1 -1  0]
 [ 2  0 -5]
 [ 3  1  6]
 [ 4  3  8]]


In [19]:
A = np.array([
[1, 2, 1],
[2, -1, 1],
[2, 1, 0]
])
b = np.transpose([2, 3, 4])
X = np.linalg.solve(A, b)
print("vd1: X = ", X)

vd1: X =  [ 1.85714286  0.28571429 -0.42857143]


In [21]:
A = np.array([
[12, 15, 10, 16, 12],
[5, 9, 14, 7, 10],
[8, 12, 10 , 9, 15]
])

A1 = A.T

price = np.array([
[2], [1], [3]
])
print(A1)
print("result = ", np.matmul(A1, price))

[[12  5  8]
 [15  9 12]
 [10 14 10]
 [16  7  9]
 [12 10 15]]
result =  [[53]
 [75]
 [64]
 [66]
 [79]]
