In [1]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
# check number of dimension
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
b = np.array([22, 26, 28, 10, 1, 2, 3])
print("\n")
print(b[:])
print(b[:2]) # 22 26 - bỏ số address cuối đi

print(b[-3:-1]) # 3 : -1 , 2: -2, 1 : -3

print(b[1:6:2]) 



[22 26 28 10  1  2  3]
[22 26]
[1 2]
[26 10  2]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

#subtract 
arrSubstract = np.subtract(arr1, arr2) #minus
#product
arrProduct = np.multiply(arr1, arr2) #product

print(arrSubstract)
print(arrProduct)

[-10  -1   8  17  26  35]
[ 200  420  660  920 1200 1500]


In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

#search = value equal 4
arr = np.array([1, 2, 4, 5,66, 44])
x = np.where(arr == 4)
print(x)

#find index if x mod 2 == 1 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

[0 1 2 3]
(array([2], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


## Day 2

In [ ]:
a = np.dot(6,12)  
print(a)

72


In [ ]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])

print(np.matmul(a, b)) #multiple of 2 matrix: 2-D

[[4 1]
 [2 2]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
 
print(np.linalg.det(arr1))

-2.0000000000000004


In [ ]:
#transpose
v1 = [1, 2, 3, 4]
v2 = [-1, 0, 1, 3]
v3 = [0, -5, 6, 8]
w = [3, -6, 17, 11]

A = np.transpose([v1, v2, v3] ) # reverse row to column

In [ ]:
print(A)

[[ 1 -1  0]
 [ 2  0 -5]
 [ 3  1  6]
 [ 4  3  8]]


In [ ]:
A = np.array([
[1, 2, 1],
[2, -1, 1],
[2, 1, 0]
])
b = np.transpose([2, 3, 4])
X = np.linalg.solve(A, b)
print("vd1: X = ", X)

vd1: X =  [ 1.85714286  0.28571429 -0.42857143]


In [ ]:
A = np.array([
[12, 15, 10, 16, 12],
[5, 9, 14, 7, 10],
[8, 12, 10 , 9, 15]
])

A1 = A.T

price = np.array([
[2], [1], [3]
])
print(A1)
print("result = ", np.matmul(A1, price))

[[12  5  8]
 [15  9 12]
 [10 14 10]
 [16  7  9]
 [12 10 15]]
result =  [[53]
 [75]
 [64]
 [66]
 [79]]


## More

In [2]:
np.array([1, 2, 3, 5])

array([1, 2, 3, 5])

In [3]:
t = np.array([3.14, 3, 2, 22])
t

array([ 3.14,  3.  ,  2.  , 22.  ])

In [4]:
np.array([1, 2, 3, 4], dtype ='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
t = np.array([range(i, i + 3)] for i in [2, 4, 6])
print(t)
type(t)

<generator object <genexpr> at 0x0000018A978572E0>


numpy.ndarray

In [6]:
a2 = np.array([[1, 2, 3],
              [3, 4, 5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
a2.dtype

dtype('int32')

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape

(2, 3)

creating numpy arrays

In [10]:
np.zeros([2, 4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones([3, 4], dtype= float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((3, 2), 3.1)
np.full((3, 2), 22)

array([[22, 22],
       [22, 22],
       [22, 22]])

In [13]:
np.arange(0, 23, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [14]:
#create an array of five values evenly spaced between 0 and 1. 
np.linspace(0, 1, 5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Random


In [15]:
np.random.random((4, 4))

array([[0.54377127, 0.96757846, 0.19905041, 0.03054199],
       [0.62647503, 0.28097221, 0.73836313, 0.11831252],
       [0.0373097 , 0.74864812, 0.94775972, 0.20819115],
       [0.79648385, 0.4887777 , 0.46886661, 0.35401706]])

In [16]:
np.random.seed(0) # no change. 
np.random.random((4, 4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [17]:
np.random.normal(0, 1, (3, 3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [18]:
np.random.randint(0, 10, (4,5)) 

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1],
       [1, 7, 9, 9, 3]])

In [19]:
np.random.rand(4, 4) 

array([[0.65314004, 0.17090959, 0.35815217, 0.75068614],
       [0.60783067, 0.32504723, 0.03842543, 0.63427406],
       [0.95894927, 0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 , 0.6235101 ]])

eye and empty


In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Linear Algebra

In [22]:
A = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]]
    )

In [23]:
B = np.array([[6, 5], [4, 3], [2,1]])
B.shape


(3, 2)

In [24]:
A.dot(B)
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [25]:
# dot product example
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))

In [26]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [27]:
#create weekly_sales dataframe
import pandas as pd
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon", "Tues", "Wed", "Thurs", "Friday"], columns= ["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Friday              1              6              7

In [28]:
#create a price array
prices = np.array([10, 8, 12])
# prices.shape

In [29]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), index=["Prices"], columns= ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [30]:
weekly_sales.shape,butter_prices.shape

((5, 3), (1, 3))

In [31]:
total_prices = weekly_sales @ butter_prices.T   
total_prices

Prices
Mon        240
Tues       138
Wed        458
Thurs      232
Friday     142

In [32]:
weekly_sales["total_prices"] = total_prices

In [33]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  total_prices
Mon                12             15              0           240
Tues                3              3              7           138
Wed                 9             19             18           458
Thurs               4              6             12           232
Friday              1              6              7           142